version: '3.7'

services:
  user_management_service:
    build: ./user_managementservice
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./movie-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/

  user_management_db:
    image: mysql:5.7
    volumes:
      - ./db/usermangement:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_ROOT_USERNAME=user_management_username
      - MYSQL_ROOT_PASSWORD=user_management_password
      - POSTGRES_DB=user_management_db

  addwish_service:
    build: ./cast-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./cast-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev

  addwish_db:
    image: mysql:5.7
    volumes:
      - ./db/addwish:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_ROOT_USERNAME=addwish_username
      - MYSQL_ROOT_PASSWORD=addwish_password
      - POSTGRES_DB=addwish_db
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - _service
      - movie_service
volumes:
  db/usermanagement:
  db/addwish:
